name: jaguar_jwt_auth
description: JWT authentication interceptor for Jaguar
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://www..com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  dart_jwt: '0.6.0'
  jaguar:
    path: ../jaguar


dev_dependencies:
  test: '>=0.12.0 <0.13.0'
